feature/84-User-Saved-Joke
Code2Gether-Discord/JokesOnYou pull request #169
Opened 2021-06-27 16:22 UTC by N1c0z

2021-08-27 12:34 UTC, chrisK00 requested changes

2021-08-27 12:34 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Controllers/SavedJokeController.cs
> +            var stuff = await _savedJokeService.GetSavedJokesByUserId(ClaimsPrincipalExtension.GetUserId(User));
stuff? xD

2021-08-27 12:34 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/SavedJoke.cs
> -        public DateTime SavedDate { get; set; } = DateTime.Now;
whats the reason for removing the = DateTime.Now? (should be DateTime.UtcNow fyi)

2021-08-27 12:34 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Repositories/SavedJokeRepository.cs
> +        public async Task AddSavedJoke(SavedJoke savedJoke) => await _context.SavedJokes.AddAsync(savedJoke).AsTask();
dont need to append .AsTask since your using await

2021-08-27 12:34 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Repositories/SavedJokeRepository.cs
> +        public async Task<IEnumerable<SavedJokeReplyDto>> GetSavedJokesByUserId(string id) => await _context.SavedJokes.Where(x => x.UserId == id).ProjectTo<SavedJokeReplyDto>(_mapper.ConfigurationPr
split this into atleast 2 lines

2021-09-21 22:01 UTC, HellHunterMax approved these changes
Good job Really well written!
I'm not sold about the own controller/Service/Repo.
Repo I understand because it has its own database entry.
Service and Controller could be put under User imo.

2021-09-21 22:01 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/SavedJokeService.cs
> +                SavedDate = System.DateTime.Now
SavedDate is not needed as it automatically done when creating a new SavedJoke.

2021-09-21 22:02 UTC, HellHunterMax commented
You have some conflicts to resolve too. Please Pull dev and resolve them.

2021-09-22 10:33 UTC, N1c0z commented
> 
> 
> Good job Really well written!
> I'm not sold about the own controller/Service/Repo.
> Repo I understand because it has its own database entry.
> Service and Controller could be put under User imo.

Hmm, imo its more organized like this
@chrisK00 opinions?

2021-09-22 11:34 UTC, chrisK00 commented
> > Good job Really well written!
> > I'm not sold about the own controller/Service/Repo.
> > Repo I understand because it has its own database entry.
> > Service and Controller could be put under User imo.
> 
> Hmm, imo its more organized like this
> @chrisK00 opinions?

Splitting up the responsibilites is important to follow SRP and provides more decoupling, easier classes to navigate. If we dont do something like this we need to switch over to MediatR. This approach also doesnt break OCP

We shouldnt stick all our logic in one class, and the responsibilites are a bit different. If we want to have more features regarding our jokes, we wouldnt put them in the jokes controller because we would run in to a OverFlowException (bad joke)

So if we think about our consumers
they get jokes on api/jokes
but to get saved jokes they get them on api/savedjokes - i think this is totally fine but the alternative is to simply extend the jokes controller. So the route would become api/jokes/saved which is a bit easier to keep track on but at the same time we still split up the classes.

The important part is that we dont nest to much because that will cause a very ugly url, but in this case i cannot see what else we would nest after the saved.

2021-09-24 02:35 UTC, HellHunterMax commented
> > > Good job Really well written!
> > > I'm not sold about the own controller/Service/Repo.
> > > Repo I understand because it has its own database entry.
> > > Service and Controller could be put under User imo.
> > 
> > 
> > Hmm, imo its more organized like this
> > @chrisK00 opinions?
> 
> Splitting up the responsibilites is important to follow SRP and provides more decoupling, easier classes to navigate. If we dont do something like this we need to switch over to MediatR. This approach also doesnt break OCP
> 
> We shouldnt stick all our logic in one class, and the responsibilites are a bit different. If we want to have more features regarding our jokes, we wouldnt put them in the jokes controller because we would run in to a OverFlowException (bad joke)
> 
> So if we think about our consumers
> they get jokes on api/jokes
> but to get saved jokes they get them on api/savedjokes - i think this is totally fine but the alternative is to simply extend the jokes controller. So the route would become api/jokes/saved which is a bit easier to keep track on but at the same time we still split up the classes.
> 
> The important part is that we dont nest to much because that will cause a very ugly url, but in this case i cannot see what else we would nest after the saved.

Thank you for the great explanation! This is where I need to learn.

2021-09-28 03:59 UTC, HellHunterMax requested changes
I think you have to revert the Migration because its still set to Postgres Database.
I get a build error because of that as well.
Maybe easiest way would be to start over from dev branching out, then copy your new code from here over to the new branch ?

Would be cool if we could remove a saved joke ?

Looks good though.

2021-09-28 03:59 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Migrations/20210626132628_SavedJokes.cs
> +using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
Not using Postgress anymore

2021-09-28 12:47 UTC, N1c0z commented on Server/JokesOnYou.Web.Api/Migrations/20210626132628_SavedJokes.cs
> +using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
oh lol, something got screwed in the dev with saved joke merge

2021-09-28 12:47 UTC, N1c0z commented on Server/JokesOnYou.Web.Api/Migrations/20210626132628_SavedJokes.cs
> +using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
thank you for pointing it out as i missed it

2021-09-30 13:01 UTC, closed without merging