Added a new component for login page
Code2Gether-Discord/JokesOnYou pull request #170
Opened 2021-08-20 04:33 UTC by PilgrimViis

2021-08-21 19:50 UTC, PilgrimViis commented
I took bye's registration page and have updated it. I've tried to merge his branch into mine, but I've failed =(  I've made a redesign if you don't mind. I want to make "Login" and "Register" buttons disabled, until the whole form would be valid. It doesn't look good with just border shadowing. Also, I've tried to take byes slider, but it looked awful on mobile, so I've switched to bootstrap switch.
![image](https://user-images.githubusercontent.com/6408195/130333296-847320d4-32e5-46b1-83d7-60fefef4a15e.png)

2021-08-22 07:03 UTC, chrisK00 requested changes
Very readable code :tada:

2021-08-22 07:03 UTC, chrisK00 commented on Client/src/app/_models/loginInfo.ts
> +  email?: string;
I think you are currently able to login either using email or username so having this named username might be more appropiate

2021-08-22 07:03 UTC, chrisK00 commented on Client/src/app/_models/registerInfo.ts
> +  dateOfBirth?: string;
Date type

2021-08-22 08:27 UTC, chrisK00 approved these changes

2021-08-23 09:08 UTC, merged