Add pagination for GetAllUser
Code2Gether-Discord/JokesOnYou pull request #193
Opened 2021-10-22 09:55 UTC by ysnarafat

closes #187

2021-10-22 14:42 UTC, chrisK00 requested changes

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Controllers/UserController.cs
> +    //[Authorize]
Why was this removed?

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Extensions/ServiceExtensions.cs
> +            services.AddDbContext<IdentityDbContext<User>>(options =>
The db has already been configured, what does this do?

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Helpers/PaginatedList.cs
> +        public int PageNumber { get; set; }
Is PageNumber not the same as CurrentPage? Or was this maybe supposed to be total pages considering the client needs to know how many pages we have. Probably want to have the amount of items aswell so the client can display something like:
found 1000 items
page 1/30

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Helpers/PaginatedList.cs
> +        public PaginatedList(List<T> items, int pageNumber, int pageSize)
Can be an IEnumerable

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Helpers/PaginatedList.cs
> +        public static async Task<PaginatedList<T>> ToPaginatedList(IQueryable<T> source, int pageNumber, int pageSize, Expression<Func<T,bool>> expression)
naming - ToPaginatedListAsync
the expression should not be sent here since the IQueryable is already passed down, we can do the filtering in our repository

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Request/Query/PaginationQuery.cs
> +    public abstract class PaginationQuery : IValidatableObject
Does not have to be abstract, sometimes we might want to use Pagination and not filtering, pagination is always required tho.

I would suggest changing the name of the class to something like PaginationParams since this is just a POCO and not directly tied to a query

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Request/Query/PaginationQuery.cs
> +        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
We could add data annotations or simply set default values in case they send weird numbers in the query

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Request/Query/UserPaginationQueryParameters.cs
> +    public class UserPaginationQueryParameters : PaginationQuery
Can be shortened to UserParameters or UserParams whatever suits you

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Repositories/Interfaces/IUserRepository.cs
> +        Task<PaginatedList<User>> GetAllUserAsync(UserPaginationQueryParameters parameters);
The naming convention and return type was changed here from
 Task<IEnumerable<UserReplyDto>> GetUsersReplyDtoAsync();
 should become
 Task<PaginatedList<UserReplyDto>> GetUsersReplyDtoAsync

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Repositories/UserRepository.cs
> +                _dbContext.Users.AsNoTracking(),
Curious: why are we using the dbcontext instead of UserManager here?

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Services/Interfaces/IUserService.cs
> +        Task<IEnumerable<UserReplyDto>> GetAll(UserPaginationQueryParameters parameters);
Should return the paginatedList so we can append the headers containing the pagination information

2021-10-22 14:42 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Services/UserService.cs
> +            return users.AsQueryable().ProjectTo<UserReplyDto>(_mapper.ConfigurationProvider);
This is a job for the repository. The repository is what is between our database provider and our application, it makes us less dependent on who is providing us with the data, this way we are breaking the repository pattern so we need to move all code that has to do with the db or EF in to the repository, the service is simply a service that is a layer made to make our controllers clean

2021-10-22 14:46 UTC, ysnarafat commented on Server/JokesOnYou.Web.Api/Controllers/UserController.cs
> +    //[Authorize]
Ah, forgot to uncomment after testing

2021-10-23 15:37 UTC, ysnarafat commented on Server/JokesOnYou.Web.Api/Helpers/PaginatedList.cs
> +        public int PageNumber { get; set; }
Yeah, I messed up somehow.

2021-10-23 15:48 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Helpers/PaginatedList.cs
> +        public int PageNumber { get; set; }
> Yeah, I messed up somehow.
No worries, if you have 0 messups then what are reviews for 😄

2021-10-23 18:14 UTC, chrisK00 requested changes
Great improvments, almost there

2021-10-23 18:14 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Controllers/UserController.cs
> +    //[Authorize]
This is still uncommented

2021-10-23 18:14 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Controllers/UserController.cs
> +using Newtonsoft.Json;
System.Text.Json is already installed so we dont need two json serializers

2021-10-23 18:14 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Request/Query/PaginationParameters.cs
> +        [RegularExpression(@"^\d*[1-9]\d*$", ErrorMessage = "PageNumber cannot be zero or negative")]
There is a range data annotation so we dont have to use regular expressions

2021-10-23 18:14 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Repositories/UserRepository.cs
> +            if (string.IsNullOrEmpty(parameters.SearchText) != true ||
this code can be written like this:
!string.IsNullOrEmpty(parameters.SearchText)
or
string.IsNullOrEmpty() == false

2021-10-23 18:59 UTC, chrisK00 approved these changes
Looks great!🥳 Well done

2021-10-23 19:02 UTC, ysnarafat commented
> Looks great!🥳 Well done

Thanks for the thorough review.

2021-10-24 04:23 UTC, HellHunterMax approved these changes
Well done cool way of doing this!

2021-10-24 13:20 UTC, merged