Add liking and unliking tag functionality
Code2Gether-Discord/JokesOnYou pull request #194
Opened 2021-10-23 03:24 UTC by JunXingLiu

2021-10-23 09:32 UTC, chrisK00 requested changes

2021-10-23 09:32 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Controllers/LikedTagsController.cs
> +        [Authorize(Roles = "Registered,Admin")]
Can be placed on top of the controller so we dont need to repeat it

2021-10-23 09:32 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Controllers/LikedTagsController.cs
> +        [HttpPut]
I would prefer to use HttpPost here, since we are creating a resource/making an action rather than fully updating an existing one. Same comments apply to the other method

2021-10-23 09:32 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Request/LikedTagsCreateDto.cs
>      public class LikedTagsCreateDto
I think we dont need this class tho considering we only need the id which should be passed in the url something like this
api/tags/like/1

2021-10-23 09:32 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Tag.cs
> +        public ICollection<User> Users { get; set; } = new List<User>();
Can we have a reference to the Users id by creating a join table instead of the actual entity?

2021-10-23 09:32 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +            _tagRepo = tagRepository;
No cheating! :P _tagRepository

2021-10-30 17:49 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Controllers/LikedTagsController.cs
> +        [Authorize(Roles = "Registered,Admin")]
done

2021-10-30 17:49 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Controllers/LikedTagsController.cs
> +        [HttpPut]
done

2021-10-30 17:49 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Models/Request/LikedTagsCreateDto.cs
>      public class LikedTagsCreateDto
done

2021-10-30 17:50 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +            _tagRepo = tagRepository;
I changed to _tagsService

2021-10-30 18:22 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Models/Tag.cs
> +        public ICollection<User> Users { get; set; } = new List<User>();
Sorry, I am pretty new to this, how can I do that?
https://www.entityframeworktutorial.net/code-first/configure-one-to-many-relationship-in-code-first.aspx
I used this site as a reference but I can't find how you could do it without creating the entity?

2021-10-30 19:26 UTC, chrisK00 commented on Server/JokesOnYou.Web.Api/Models/Tag.cs
> +        public ICollection<User> Users { get; set; } = new List<User>();
Correct me if im wrong I was looking for an example where we have already done this, and there seems to be a entity for this feature

https://github.com/Code2Gether-Discord/JokesOnYou/blob/dev/Server/JokesOnYou.Web.Api/Models/LikedTags.cs

Anyhow the general approach is just like how you would do a many to many in sql. You have a User table, You have a Tag table, then you have UserLikedTag table which holds a reference to the user_id and the tag_id.

2021-11-02 03:36 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Models/Tag.cs
> +        public ICollection<User> Users { get; set; } = new List<User>();
@JunXingLiu in Nico's PR you can see how he did it:
[Saved Jokes PR] (https://github.com/Code2Gether-Discord/JokesOnYou/pull/190/files)

2021-11-08 05:42 UTC, HellHunterMax requested changes
So because Tag has not been implemented yet this is not going to work as intended.
With this you will only be able to like a tag globally and not a tag Linked to a joke.

so for example you have a joke on the website and underneath the joke you see some tags associated with the joke. you have the option to press on a tag and Like it.
This will then tell the system you thought the Tag is a good Tag for the joke.

but with some small tweaks this could function perfectly when we finally implement the Tag feature.

great job everything works as expected.
i would rename the LikedTags.
and add some more info to the exception messages.

2021-11-08 05:42 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +                throw new AppException("Tag wasn't liked by user");
Maybe add some more info in this exception, like which tag and which user?

2021-11-08 05:42 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +            LikedTags likedTags = await _likedTagsRepo.GetLikedTag(userId, tagID);
LikedTags Should be changed to TagLike or LikedTag or LikeForTag but my vote goes do the Last one.
1. its a Tag Like, (a like for a tag). Not a Liked tag (a tag that has been liked). the object is the like not the tag.
2. its singular not muliple likedTags anymore.
3. LikeForTag makes it clear that its a like for a tag.

I hope this is clear.

2021-11-08 05:42 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +        public async Task<LikedTagsReplyDto> LikeTagAsync(int tagID, string userId)
tagId not tagID. just a small tweak.

2021-11-11 22:06 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +                throw new AppException("Tag wasn't liked by user");
done

2021-11-11 22:07 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +            LikedTags likedTags = await _likedTagsRepo.GetLikedTag(userId, tagID);
Done, I used likeForTag.

2021-11-11 22:07 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
> +        public async Task<LikedTagsReplyDto> LikeTagAsync(int tagID, string userId)
done

2021-11-11 23:58 UTC, HellHunterMax requested changes
The model LikedTags should imo be renamed to LikeForTag.
Its not a LikedTags (the s making it multiple) anymore.
So there should be some more changes all over but just the name. and also controller names and stuff. @chrisK00  what do you think ?

2021-11-12 01:28 UTC, JunXingLiu commented
> The model LikedTags should imo be renamed to LikeForTag. Its not a LikedTags (the s making it multiple) anymore. So there should be some more changes all over but just the name. and also controller names and stuff. @chrisK00 what do you think ?

Should I change it for Repo and Services? from LikedTagsRepository -> LikedTagRepository

2021-11-12 01:31 UTC, HellHunterMax commented
> > The model LikedTags should imo be renamed to LikeForTag. Its not a LikedTags (the s making it multiple) anymore. So there should be some more changes all over but just the name. and also controller names and stuff. @chrisK00 what do you think ?
> 
> Should I change it for Repo and Services? from LikedTagsRepository -> LikedTagRepository

Repo, services, controller and model.
LikeForTagsRepository in my opinion... and change the model to a LikeForTag so then everything is named the same way.

2021-11-12 02:00 UTC, JunXingLiu commented
> > > The model LikedTags should imo be renamed to LikeForTag. Its not a LikedTags (the s making it multiple) anymore. So there should be some more changes all over but just the name. and also controller names and stuff. @chrisK00 what do you think ?
> > 
> > 
> > Should I change it for Repo and Services? from LikedTagsRepository -> LikedTagRepository
> 
> Repo, services, controller and model. LikeForTagsRepository in my opinion... and change the model to a LikeForTag so then everything is named the same way.

I changed it. Hmm should the DB table be changed as well or that can remain?

2021-11-12 02:07 UTC, JunXingLiu commented
Crap, that's weird. It compiled fine on my computer... how do I fix those reference errors?

2021-11-12 02:37 UTC, HellHunterMax commented
> > > > The model LikedTags should imo be renamed to LikeForTag. Its not a LikedTags (the s making it multiple) anymore. So there should be some more changes all over but just the name. and also controller names and stuff. @chrisK00 what do you think ?
> > > 
> > > 
> > > Should I change it for Repo and Services? from LikedTagsRepository -> LikedTagRepository
> > 
> > 
> > Repo, services, controller and model. LikeForTagsRepository in my opinion... and change the model to a LikeForTag so then everything is named the same way.
> 
> I changed it. Hmm should the DB table be changed as well or that can remain?

Yes the database table name should be the same as the model.

2021-11-12 03:23 UTC, JunXingLiu commented
> > > > > The model LikedTags should imo be renamed to LikeForTag. Its not a LikedTags (the s making it multiple) anymore. So there should be some more changes all over but just the name. and also controller names and stuff. @chrisK00 what do you think ?
> > > > 
> > > > 
> > > > Should I change it for Repo and Services? from LikedTagsRepository -> LikedTagRepository
> > > 
> > > 
> > > Repo, services, controller and model. LikeForTagsRepository in my opinion... and change the model to a LikeForTag so then everything is named the same way.
> > 
> > 
> > I changed it. Hmm should the DB table be changed as well or that can remain?
> 
> Yes the database table name should be the same as the model.

Done!

2021-11-17 05:22 UTC, HellHunterMax commented
I just created the UserJokeTag that is actually needed for this issue.
Please review #207 Then we can edit this one to use UserJokeTag for liking.

2021-11-20 19:42 UTC, JunXingLiu commented
> I just created the UserJokeTag that is actually needed for this issue. Please review #207 Then we can edit this one to use UserJokeTag for liking.

Should I modify my code so it uses UserJokeTag? or that is another issue?

2021-11-20 19:58 UTC, HellHunterMax commented
Yes that would be best imo I'll merge to  dev.

2021-11-22 04:27 UTC, JunXingLiu commented
> Yes that would be best imo I'll merge to dev.

I think I got it working. Please take a look.

2021-11-23 17:57 UTC, HellHunterMax approved these changes
Great job! Thanks for all the edits!

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Models/Request/LikeForTagCreateDto.cs
> +    public class LikeForTagCreateDto
This is not being used so can be removed ?

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Models/Request/UnlikedTagCreateDto.cs
> +    public class UnlikedTagCreateDto
same goes for this one. not being used ?

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/LikeForTagsService.cs
> +            var tagReplyDto = _mapper.Map<TagReplyDto>(tag);
This would return the likes from the tag. while what we need are the likes from the UserJokeTag.

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/TagService.cs
> +                tagReplyDto = await _likeForTagsService.ToggleLikeForTag(userJokeTag, userId); // add initial like to LikeForTag
Lets put this duplicate line Under the if/else statement.

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/TagService.cs
> +                tag.Likes = 0;
we can remove this line as an int defaults to 0.

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Repositories/LikeForTagsRepository.cs
> +        public async Task<IEnumerable<LikeForTag>> GetLikedTagByUserId(string userId) =>
Lets call this GetLikedTagsByUserId. The Added S telling us that this is multiple.

And TBH we did it wrong in all our Repos, Services and Controllers. it should just be called GetByUserId as we are inside the LikeForTags Repository we will of course return a LikeForTag would be weird to return something else.

2021-11-23 17:57 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Controllers/LikeForTagsController.cs
> +            return tagReplyDto;
Maybe we should just return An Ok or a NoContent() depending on the like or Unlike ?

2021-11-23 17:59 UTC, HellHunterMax commented
I see I still had some unpushed comments ready. You could fix those as well if you want to make it complete.

2021-11-23 18:11 UTC, JunXingLiu commented
> I see I still had some unpushed comments ready. You could fix those as well if you want to make it complete.

I'll get those out of the way

2021-11-23 19:34 UTC, JunXingLiu commented on Server/JokesOnYou.Web.Api/Services/LikeForTagsService.cs
> +            var tagReplyDto = _mapper.Map<TagReplyDto>(tag);
on line 77: tagReplyDto.Likes = userJokeTag.Likes
Do you think this will be okay?

2021-11-23 20:41 UTC, HellHunterMax commented on Server/JokesOnYou.Web.Api/Services/LikeForTagsService.cs
> +            var tagReplyDto = _mapper.Map<TagReplyDto>(tag);
yes

2021-11-24 07:44 UTC, chrisK00 approved these changes

2021-11-24 16:08 UTC, merged